CREATE SCHEMA IF NOT EXISTS NEXTDIGITAL;

CREATE TABLE IF NOT EXISTS NEXTDIGITAL.CONTA_CONTABIL_OPERADORA (
    ID BIGINT PRIMARY KEY,
    NOME_FILIAL VARCHAR(22),
    DESCRICAO_LEGADO VARCHAR(255),
    CODIGO_LEGADO VARCHAR(255),
    SISTEMA_LEGADO VARCHAR(255),
    DESCRICAO_PROTHEUS VARCHAR(255),
    CODIGO_PROTHEUS VARCHAR(255),
    COLUMN8 VARCHAR(4),
    FILIAL BIGINT,
    COD_CONTA_PROTHEUS VARCHAR(5),
    ID_BANCO_PROTHEUS VARCHAR(23),
    NUMERO_BANCO_PROTHEUS VARCHAR(3),
    AGENCIA_PROTHEUS BIGINT,
    DV_AGENCIA_PROTHEUS VARCHAR(1),
    NUMERO_CONTA_PROTHEUS BIGINT,
    DV_CONTA_PROTHEUS VARCHAR(1),
    NOME_BANCO_PROTHEUS VARCHAR(14),
    COD_CONTA_LEGADO BIGINT,
    ID_BANCO_LEGADO BIGINT,
    NUMERO_BANCO_LEGADO VARCHAR(1),
    AGENCIA_LEGADO BIGINT,
    DV_AGENCIA_LEGADO VARCHAR(1),
    NUMERO_CONTA_LEGADO BIGINT,
    DV_CONTA_LEGADO VARCHAR(1),
    NOME_BANCO_LEGADO VARCHAR(14)
);

CREATE TABLE IF NOT EXISTS NEXTDIGITAL.CENTRO_CUSTO (
    ID BIGINT PRIMARY KEY,
    NOME_FILIAL VARCHAR(22),
    DESCRICAO_LEGADO VARCHAR(255),
    CODIGO_LEGADO VARCHAR(255),
    SISTEMA_LEGADO VARCHAR(255),
    DESCRICAO_PROTHEUS VARCHAR(255),
    CODIGO_PROTHEUS VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS NEXTDIGITAL.FILIAL (
    ID BIGINT PRIMARY KEY,
    CODIGO_PROTHEUS VARCHAR(8) NOT NULL,
    NOME VARCHAR(500) NOT NULL,
    CNPJ VARCHAR(14) NOT NULL,
    ENDERECO VARCHAR(1000),
    COMPLEMENTO VARCHAR(1000),
    BAIRRO VARCHAR(250),
    CIDADE VARCHAR(100),
    UF VARCHAR(2)
);
